project:
  type: website
  output-dir: docs
  resources:
    - "assets/*"


lang: en
website:
  title: "Projects’ workflow for reproducibility and replicability using R"
  site-url: https://e-kotov.github.io/2025-mpidr-open-science-reproducible-workflows/
  repo-url: https://github.com/e-kotov/2025-mpidr-open-science-reproducible-workflows
  page-navigation: true
  page-footer: 
      border: true
      left: "Authors: Egor Kotov & Jonas Schöley" 
      center:
       - license.qmd
      right: 
        - icon: github
          href: https://github.com/e-kotov/2025-mpidr-open-science-reproducible-workflows

  sidebar:
    style: "docked"
    search: true
    tools: 
      - icon: github
        text: Github
        href: https://github.com/e-kotov/2025-mpidr-open-science-reproducible-workflows
    contents:
      - index.qmd
      - 1-r-packages.qmd
      - 2-analysis-pipeline.qmd
      - section: "3. Containerizing R and R Packages for Ultimate Reproducibility"
        contents:
          - 3-containers.qmd
          - 3a-how-docker-and-binder-work.qmd
          - 3b-reproducible-github-repo-in-binder.qmd
          - 3c-build-docker-container-image.qmd


authors:
  - name: Egor Kotov
    url: https://www.ekotov.pro/
    orcid: 0000-0001-6690-5345
    affiliations:
      - ref: mpidr
      - ref: upf
  - name: Jonas Schöley
    url: https://www.demogr.mpg.de/de/ueber_uns_6113/mitarbeiter_innen_1899/jonas_schoeley_2341/
    orcid: 0000-0002-3340-8518
    affiliations:
      - ref: mpidr

affiliations:
  - id: mpidr
    name: Max Planck Institute for Demographic Research
    city: Rostock
    country: Germany
    url: https://demogr.mpg.de/
  - id: upf
    name: Universitat Pompeu Fabra
    city: Barcelona
    country: Spain
    url: https://www.upf.edu/


format:
  html:
    link-external-icon: true
    include-in-header:
        file: analytics.html
    theme:
      light: zephyr
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4
    toc-location: right
    code-overflow: wrap
    grid:
      body-width: 800px
    mermaid:
      theme: neutral

bibliography: references.bib
bibliographystyle: mla

editor: source

editor_options:
  markdown:
    wrap: 72
    canonical: true

execute:
  freeze: auto
