---
title: "Workshop Introduction"

authors:
  - name: Egor Kotov
    url: https://www.ekotov.pro/
    orcid: 0000-0001-6690-5345
    affiliations:
      - ref: mpidr
      - ref: upf
  - name: Jonas Schöley
    url: https://www.demogr.mpg.de/de/ueber_uns_6113/mitarbeiter_innen_1899/jonas_schoeley_2341/
    orcid: 0000-0002-3340-8518
    affiliations:
      - ref: mpidr

affiliations:
  - id: mpidr
    name: Max Planck Institute for Demographic Research
    city: Rostock
    country: Germany
    url: https://demogr.mpg.de/
  - id: upf
    name: Universitat Pompeu Fabra
    city: Barcelona
    country: Spain
    url: https://www.upf.edu/

---

This website provides supporting materials for the part 2 of the workshop **Projects’ workflow for reproducibility and replicability using R** held at the [Second Rostock Open Science Workshop](https://www.demogr.mpg.de/en/news_events_6123/calendar_1921/second_rostock_open_science_workshop_13282){target="_blank"} organized by the [Max Planck Institute for Demographic Research](https://demogr.mpg.de/){target="_blank"} in Rostock, Germany. This tutorial is [licensed under CC0](license.qmd).

This tutorial includes the following sections:

1. ["R packages version management with `renv` and `pak`"](1-r-packages.qmd), which covers [`{renv}`](https://rstudio.github.io/renv/){target="_blank"} and [`{pak}`](https://pak.r-lib.org/){target="_blank"} for `R` packages version management;
2. ["Building analysis pipelines with `targets`"](2-analysis-pipeline.qmd), which covers the [`{targets}`](https://docs.ropensci.org/targets/){target="_blank"} R package for structuring the analysis code in a clean and modular way;
3. ["Containerizing R and R Packages for Ultimate Reproducibility"](3-containers.qmd), which covers `Docker` (or `Docker`-compatible tools) for building containers that include all operating system files, R installation, any additional system depenencies and R packages in a single file that can be used to run the analysis even if some software becomes outdated or even unavailable for installation in the future.

To participate in the workshop, we recommend that you have a [GitHub](https://github.com/){target="_blank"} account and a [Docker Hub](https://hub.docker.com/){target="_blank"} account (the latter is optional and only needed for the last section on `Docker`).

For the section 3 on `Docker`, you may also want to install [Docker](https://docs.docker.com/get-docker/){target="_blank"} on your computer (for Windows, macOS or Linux). For macOS we also highly recommend the free version of [OrbStack](https://orbstack.dev/download){target="_blank"} as a complete and lightweight Docker Desktop replacement. In the workshop we will also show how to try `Docker` using just a web browser and the website [https://labs.play-with-docker.com/](https://labs.play-with-docker.com/){target="_blank"} without installing any additional software on your computer.

## Expected learning outcomes

- Able to explain why it is important to track the versions of software that are used for the analysis

- Able to use `{renv}` and `{pak}` to setup a project directory with specific R package versions

- Able to explain the advantages of structuring the analysis code in a modular way

- Able to use `{targets}` to setup a modular analysis pipeline

- Able to explain the concept of containers and their role in computational reproducibility and discuss further reproducibility challenges

- Able to create a Docker container with `RStudio` and `R` of a specific version and install the `R` packages previously saved with `{renv}` and `{pak}` into the container

- (optional) Able to create a GitHub repository that can be executed in the cloud using [Binder](https://mybinder.org/){target="_blank"}
